language: ruby
rvm:
  - 2.2.4
  - jruby-19mode
  - jruby-head
  - ruby-head
  - ree
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ree
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email: true
